// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MarketingBox.Reporting.Service.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210909133913_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("affiliate-service")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("MarketingBox.Affiliate.Postgres.Entities.PartnerEntity", b =>
                {
                    b.Property<long>("AffiliateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("AffiliateId");

                    b.HasIndex("TenantId", "AffiliateId");

                    b.ToTable("partners");
                });

            modelBuilder.Entity("MarketingBox.Affiliate.Postgres.Entities.PartnerEntity", b =>
                {
                    b.OwnsOne("MarketingBox.Affiliate.Postgres.Entities.PartnerBank", "Bank", b1 =>
                        {
                            b1.Property<long>("PartnerEntityAffiliateId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("AccountNumber")
                                .HasColumnType("text");

                            b1.Property<string>("BankAddress")
                                .HasColumnType("text");

                            b1.Property<string>("BankName")
                                .HasColumnType("text");

                            b1.Property<string>("BeneficiaryAddress")
                                .HasColumnType("text");

                            b1.Property<string>("BeneficiaryName")
                                .HasColumnType("text");

                            b1.Property<string>("Iban")
                                .HasColumnType("text");

                            b1.Property<string>("Swift")
                                .HasColumnType("text");

                            b1.HasKey("PartnerEntityAffiliateId");

                            b1.ToTable("partners");

                            b1.WithOwner()
                                .HasForeignKey("PartnerEntityAffiliateId");
                        });

                    b.OwnsOne("MarketingBox.Affiliate.Postgres.Entities.PartnerCompany", "Company", b1 =>
                        {
                            b1.Property<long>("PartnerEntityAffiliateId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Address")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("RegNumber")
                                .HasColumnType("text");

                            b1.Property<string>("VatId")
                                .HasColumnType("text");

                            b1.HasKey("PartnerEntityAffiliateId");

                            b1.ToTable("partners");

                            b1.WithOwner()
                                .HasForeignKey("PartnerEntityAffiliateId");
                        });

                    b.OwnsOne("MarketingBox.Affiliate.Postgres.Entities.PartnerGeneralInfo", "GeneralInfo", b1 =>
                        {
                            b1.Property<long>("PartnerEntityAffiliateId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Currency")
                                .HasColumnType("integer");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Password")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.Property<int>("Role")
                                .HasColumnType("integer");

                            b1.Property<string>("Skype")
                                .HasColumnType("text");

                            b1.Property<int>("State")
                                .HasColumnType("integer");

                            b1.Property<string>("Username")
                                .HasColumnType("text");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("text");

                            b1.HasKey("PartnerEntityAffiliateId");

                            b1.ToTable("partners");

                            b1.WithOwner()
                                .HasForeignKey("PartnerEntityAffiliateId");
                        });

                    b.Navigation("Bank");

                    b.Navigation("Company");

                    b.Navigation("GeneralInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
